"""core ledger tables

Revision ID: 8f8c2590d28d
Revises: 
Create Date: 2026-08-19 01:38:17.147351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f8c2590d28d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparty',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('counterparty_type', sa.Enum('INDIVIDUAL', 'LAW_FIRM', 'ACCOUNTING_FIRM', 'FUND_MANAGER', 'SPONSOR', 'BROKER', 'OTHER', name='counterpartytype', native_enum=False), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.Enum('INDIVIDUAL', 'TRUST', 'LLC', 'PARTNERSHIP', 'CORPORATION', 'JOINT', name='entitytype', native_enum=False), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('formation_date', sa.Date(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.Enum('PRIVATE_STOCK', 'SAFE_NOTE', 'CONVERTIBLE_NOTE', 'REAL_PROPERTY', 'LLC_INTEREST', 'PE_FUND', 'VC_FUND_LP', 'CRYPTO', 'ARTWORK', 'OTHER', name='assettype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXITED', 'WRITTEN_OFF', name='investmentstatus', native_enum=False), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('initial_investment_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('current_valuation', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valuation_date', sa.Date(), nullable=True),
    sa.Column('valuation_source', sa.Enum('MANUAL', 'THIRD_PARTY', 'MARK', name='valuationsource', native_enum=False), nullable=True),
    sa.Column('type_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', 'VIEWER', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('investment_counterparty',
    sa.Column('investment_id', sa.Uuid(), nullable=False),
    sa.Column('counterparty_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('FUND_MANAGER', 'SPONSOR', 'LEGAL_COUNSEL', 'ACCOUNTANT', 'AUDITOR', 'BROKER', 'OTHER', name='counterpartyrole', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_counterparty_counterparty_id'), 'investment_counterparty', ['counterparty_id'], unique=False)
    op.create_index(op.f('ix_investment_counterparty_investment_id'), 'investment_counterparty', ['investment_id'], unique=False)
    op.create_table('ownership',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('investment_id', sa.Uuid(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('units', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('ownership_type', sa.Enum('DIRECT', 'INDIRECT', name='ownershiptype', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownership_entity_id'), 'ownership', ['entity_id'], unique=False)
    op.create_index(op.f('ix_ownership_investment_id'), 'ownership', ['investment_id'], unique=False)
    op.create_table('transaction',
    sa.Column('investment_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sa.Enum('CAPITAL_CALL', 'CONTRIBUTION', 'DISTRIBUTION', 'PURCHASE', 'SALE', 'VALUATION_UPDATE', 'FEE', 'TRANSFER', name='transactiontype', native_enum=False), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('units_delta', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('price_per_unit', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('counterparty_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_entity_id'), 'transaction', ['entity_id'], unique=False)
    op.create_index(op.f('ix_transaction_investment_id'), 'transaction', ['investment_id'], unique=False)
    op.create_table('document',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Enum('K1', 'SUBSCRIPTION_AGREEMENT', 'SAFE_NOTE', 'OPERATING_AGREEMENT', 'CAPITAL_CALL_NOTICE', 'STATEMENT', 'TAX_FORM', 'VALUATION_REPORT', 'OTHER', name='documenttype', native_enum=False), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'REVIEWED', 'APPROVED', 'ARCHIVED', name='documentstatus', native_enum=False), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('investment_id', sa.Uuid(), nullable=True),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('entity_id IS NOT NULL OR investment_id IS NOT NULL OR transaction_id IS NOT NULL', name='ck_document_has_linked_record'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investment.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # 'transaction' and 'document' reference each other; document_id's FK is added
    # here, after both tables exist, since op.create_table() silently drops
    # use_alter=True constraints instead of deferring them.
    op.create_foreign_key(
        'fk_transaction_document_id', 'transaction', 'document', ['document_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transaction_document_id', 'transaction', type_='foreignkey')
    op.drop_table('document')
    op.drop_index(op.f('ix_transaction_investment_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_entity_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_ownership_investment_id'), table_name='ownership')
    op.drop_index(op.f('ix_ownership_entity_id'), table_name='ownership')
    op.drop_table('ownership')
    op.drop_index(op.f('ix_investment_counterparty_investment_id'), table_name='investment_counterparty')
    op.drop_index(op.f('ix_investment_counterparty_counterparty_id'), table_name='investment_counterparty')
    op.drop_table('investment_counterparty')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('investment')
    op.drop_table('entity')
    op.drop_table('counterparty')
    # ### end Alembic commands ###
